name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser
      - name: Run Update Python Script
        run: |
          python main.py
      - name: Configure git user
        run: |
          git config --local user.email "so1gging@gmail.com"
          git config --local user.name "so1gging"
      - name: Pull latest changes
        run: |
          git fetch origin main
          git rebase origin/main
      - name: Commit and push changes
        run: |
          git add README.md
          git diff --cached --quiet || git commit -m "Update README.md"
          git push origin main
