name: Python application

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # 매일 자정 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Run Update Python Script
        run: |
          python main.py

      - name: Configure git user
        run: |
          git config --local user.email "so1gging@gmail.com"
          git config --local user.name "so1gging"

      - name: Commit README.md if changed
        run: |
          git add README.md
          git diff --cached --quiet || git commit -m "Update README.md"

      - name: Pull latest changes (rebase)
        run: |
          git fetch origin main
          git rebase origin/main

      - name: Push changes
        run: git push origin main
